// Generated from scaffolding/components/*.json. Do not edit manually.
namespace Mockups.DesktopEditorShell.EditorShell;

public static class GeneratedComponentScaffoldEmbeddedSlots
{
    public static EmbeddedComponentSlotDefinition[] All { get; } =
    [
        new(
            "component.audio.avatar.editor",
            "avatar",
            "Avatar",
            "component.avatar",
            ["audio", "avatarSlot", "componentSlot"],
            true),
        new(
            "component.audio.badge.editor",
            "badge",
            "Badge",
            "component.badge",
            ["audio", "badgeSlot", "componentSlot"],
            true),
        new(
            "component.audio.durationLabel.editor",
            "label",
            "Duration label",
            "component.label",
            ["audio", "durationLabelSlot"],
            true),
        new(
            "component.audio.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["audio", "surfaceSlot"],
            true),
        new(
            "component.avatar.badge.editor",
            "badge",
            "Badge",
            "component.badge",
            ["avatar", "badgeSlot", "componentSlot"],
            true),
        new(
            "component.avatar.label.editor",
            "label",
            "Label",
            "component.label",
            ["avatar", "labelSlot", "componentSlot"],
            true),
        new(
            "component.bubble.actorLabel.editor",
            "label",
            "Actor label",
            "component.label",
            ["bubble", "actorLabelSlot", "componentSlot"],
            true),
        new(
            "component.bubble.avatar.editor",
            "avatar",
            "Avatar",
            "component.avatar",
            ["bubble", "avatarSlot", "componentSlot"],
            true),
        new(
            "component.bubble.media.audio.editor",
            "audio",
            "Audio media",
            "component.audio",
            ["bubble", "audioSlot"],
            true),
        new(
            "component.bubble.media.image.editor",
            "media",
            "Image media",
            "component.media",
            ["bubble", "imageMediaSlot"],
            true),
        new(
            "component.bubble.media.video.editor",
            "media",
            "Video media",
            "component.media",
            ["bubble", "videoMediaSlot"],
            true),
        new(
            "component.bubble.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["bubble", "surfaceSlot"],
            true),
        new(
            "component.bubble.textBox.editor",
            "textBox",
            "Text box",
            "component.textBox",
            ["bubble", "textBoxSlot"],
            true),
        new(
            "component.button.appearance.label.editor",
            "label",
            "Normal label",
            "component.label",
            ["button", "appearance", "labelSlot"],
            true),
        new(
            "component.button.appearance.surface.editor",
            "surface",
            "Normal surface",
            "component.surface",
            ["button", "appearance", "surfaceSlot"],
            true),
        new(
            "component.button.badge.editor",
            "badge",
            "Badge",
            "component.badge",
            ["button", "badgeSlot"],
            true),
        new(
            "component.callParticipant.avatar",
            "avatar",
            "Avatar",
            "component.avatar",
            ["callParticipant", "avatarSlot"],
            true),
        new(
            "component.callParticipant.media",
            "media",
            "Media",
            "component.media",
            ["callParticipant", "mediaSlot"],
            true),
        new(
            "component.callParticipant.nameLabel",
            "label",
            "Name label",
            "component.label",
            ["callParticipant", "nameLabelSlot"],
            true),
        new(
            "component.callParticipant.statusLabel",
            "label",
            "Status label",
            "component.label",
            ["callParticipant", "statusLabelSlot"],
            true),
        new(
            "component.callParticipant.surface",
            "surface",
            "Surface",
            "component.surface",
            ["callParticipant", "surfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.correct.empty.editor",
            "surface",
            "Correct empty",
            "component.surface",
            ["codeIndicator", "states", "correct", "emptySurfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.correct.filled.editor",
            "surface",
            "Correct filled",
            "component.surface",
            ["codeIndicator", "states", "correct", "filledSurfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.incorrect.empty.editor",
            "surface",
            "Incorrect empty",
            "component.surface",
            ["codeIndicator", "states", "incorrect", "emptySurfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.incorrect.filled.editor",
            "surface",
            "Incorrect filled",
            "component.surface",
            ["codeIndicator", "states", "incorrect", "filledSurfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.initial.empty.editor",
            "surface",
            "Initial empty",
            "component.surface",
            ["codeIndicator", "states", "initial", "emptySurfaceSlot"],
            true),
        new(
            "component.codeIndicator.states.initial.filled.editor",
            "surface",
            "Initial filled",
            "component.surface",
            ["codeIndicator", "states", "initial", "filledSurfaceSlot"],
            true),
        new(
            "component.gallery.media.editor",
            "media",
            "Media item",
            "component.media",
            ["gallery", "mediaSlot"],
            true),
        new(
            "component.gallery.surface.editor",
            "surface",
            "Gallery surface",
            "component.surface",
            ["gallery", "surfaceSlot"],
            true),
        new(
            "component.iconBar.activeCenterIconRow.editor",
            "iconRow",
            "Active center row",
            "component.iconRow",
            ["iconBar", "activeCenterIconRowSlot"],
            true),
        new(
            "component.iconBar.activeLeftIconRow.editor",
            "iconRow",
            "Active left row",
            "component.iconRow",
            ["iconBar", "activeLeftIconRowSlot"],
            true),
        new(
            "component.iconBar.activeRightIconRow.editor",
            "iconRow",
            "Active right row",
            "component.iconRow",
            ["iconBar", "activeRightIconRowSlot"],
            true),
        new(
            "component.iconBar.idleCenterIconRow.editor",
            "iconRow",
            "Idle center row",
            "component.iconRow",
            ["iconBar", "idleCenterIconRowSlot"],
            true),
        new(
            "component.iconBar.idleLeftIconRow.editor",
            "iconRow",
            "Idle left row",
            "component.iconRow",
            ["iconBar", "idleLeftIconRowSlot"],
            true),
        new(
            "component.iconBar.idleRightIconRow.editor",
            "iconRow",
            "Idle right row",
            "component.iconRow",
            ["iconBar", "idleRightIconRowSlot"],
            true),
        new(
            "component.incomingCallNotification.avatar",
            "avatar",
            "Avatar",
            "component.avatar",
            ["incomingCallNotification", "avatarSlot"],
            true),
        new(
            "component.incomingCallNotification.iconRow",
            "iconRow",
            "Icon Row",
            "component.iconRow",
            ["incomingCallNotification", "iconRowSlot"],
            true),
        new(
            "component.incomingCallNotification.surface",
            "surface",
            "Surface",
            "component.surface",
            ["incomingCallNotification", "surfaceSlot"],
            true),
        new(
            "component.keyboard.iconBar.editor",
            "iconBar",
            "Icon bar",
            "component.iconBar",
            ["keyboard", "iconBarSlot"],
            true),
        new(
            "component.keypad.label.editor",
            "label",
            "Label",
            "component.label",
            ["keypad", "labelSlot"],
            true),
        new(
            "component.label.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["label", "surfaceSlot"],
            true),
        new(
            "component.list.collectionStack",
            "collectionStack",
            "Collection Stack",
            "component.collectionStack",
            ["list", "collectionStackSlot"],
            true),
        new(
            "component.list.listItem",
            "listItem",
            "List Item",
            "component.listItem",
            ["list", "listItemSlot"],
            true),
        new(
            "component.list.surface",
            "surface",
            "Surface",
            "component.surface",
            ["list", "surfaceSlot"],
            true),
        new(
            "component.listItem.components.avatar.component",
            "avatar",
            "Avatar",
            "component.avatar",
            ["listItem", "components", "avatar", "componentSlot"],
            true),
        new(
            "component.listItem.components.iconRow.component",
            "iconRow",
            "Icon Row",
            "component.iconRow",
            ["listItem", "components", "iconRow", "componentSlot"],
            true),
        new(
            "component.listItem.components.label.component",
            "label",
            "Label",
            "component.label",
            ["listItem", "components", "label", "componentSlot"],
            true),
        new(
            "component.listItem.states.inactive.surface",
            "surface",
            "Inactive surface",
            "component.surface",
            ["listItem", "states", "inactive", "surfaceSlot"],
            true),
        new(
            "component.listItem.states.normal.surface",
            "surface",
            "Normal surface",
            "component.surface",
            ["listItem", "states", "normal", "surfaceSlot"],
            true),
        new(
            "component.listItem.states.pressed.surface",
            "surface",
            "Pressed surface",
            "component.surface",
            ["listItem", "states", "pressed", "surfaceSlot"],
            true),
        new(
            "component.media.fullScreenBottomIconBar.editor",
            "iconBar",
            "Full screen bottom icon bar",
            "component.iconBar",
            ["media", "fullScreenBottomIconBarSlot"],
            true),
        new(
            "component.media.fullScreenCenterIconBar.editor",
            "iconBar",
            "Full screen center icon bar",
            "component.iconBar",
            ["media", "fullScreenCenterIconBarSlot"],
            true),
        new(
            "component.media.fullScreenTopIconBar.editor",
            "iconBar",
            "Full screen top icon bar",
            "component.iconBar",
            ["media", "fullScreenTopIconBarSlot"],
            true),
        new(
            "component.media.idleText.label.editor",
            "label",
            "Idle label",
            "component.label",
            ["media", "idleText", "labelSlot"],
            true),
        new(
            "component.media.inlineBottomIconBar.editor",
            "iconBar",
            "Inline bottom icon bar",
            "component.iconBar",
            ["media", "inlineBottomIconBarSlot"],
            true),
        new(
            "component.media.inlineCenterIconBar.editor",
            "iconBar",
            "Inline center icon bar",
            "component.iconBar",
            ["media", "inlineCenterIconBarSlot"],
            true),
        new(
            "component.media.inlineTopIconBar.editor",
            "iconBar",
            "Inline top icon bar",
            "component.iconBar",
            ["media", "inlineTopIconBarSlot"],
            true),
        new(
            "component.media.playText.label.editor",
            "label",
            "Play label",
            "component.label",
            ["media", "playText", "labelSlot"],
            true),
        new(
            "component.media.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["media", "surfaceSlot"],
            true),
        new(
            "component.notification.avatar.editor",
            "avatar",
            "Avatar",
            "component.avatar",
            ["notification", "avatarSlot"],
            true),
        new(
            "component.notification.detailLabel.editor",
            "label",
            "Detail label",
            "component.label",
            ["notification", "detailLabelSlot"],
            true),
        new(
            "component.notification.summaryLabel.editor",
            "label",
            "Summary label",
            "component.label",
            ["notification", "summaryLabelSlot"],
            true),
        new(
            "component.notification.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["notification", "surfaceSlot"],
            true),
        new(
            "component.notifications.badge.editor",
            "badge",
            "Badge",
            "component.badge",
            ["notifications", "badgeSlot"],
            true),
        new(
            "component.notifications.collectionStack.editor",
            "collectionStack",
            "Collection Stack",
            "component.collectionStack",
            ["notifications", "collectionStackSlot"],
            true),
        new(
            "component.notifications.notification.editor",
            "notification",
            "Notification",
            "component.notification",
            ["notifications", "notificationSlot"],
            true),
        new(
            "component.password.correctLabel.editor",
            "label",
            "Correct label",
            "component.label",
            ["password", "correctLabelSlot"],
            true),
        new(
            "component.password.drawPassword.editor",
            "drawPassword",
            "Draw password",
            "component.drawPassword",
            ["password", "drawPasswordSlot"],
            true),
        new(
            "component.password.faceRecognition.editor",
            "faceRecognition",
            "Face recognition",
            "component.faceRecognition",
            ["password", "faceRecognitionSlot"],
            true),
        new(
            "component.password.fingerprint.editor",
            "fingerprint",
            "Fingerprint",
            "component.fingerprint",
            ["password", "fingerprintSlot"],
            true),
        new(
            "component.password.iconBar.editor",
            "iconBar",
            "Icon bar",
            "component.iconBar",
            ["password", "iconBarSlot"],
            true),
        new(
            "component.password.incorrectLabel.editor",
            "label",
            "Incorrect label",
            "component.label",
            ["password", "incorrectLabelSlot"],
            true),
        new(
            "component.password.indicator.editor",
            "codeIndicator",
            "Code indicator",
            "component.codeIndicator",
            ["password", "indicatorSlot"],
            true),
        new(
            "component.password.initialLabel.editor",
            "label",
            "Initial label",
            "component.label",
            ["password", "initialLabelSlot"],
            true),
        new(
            "component.password.keypad.editor",
            "keypad",
            "Keypad",
            "component.keypad",
            ["password", "keypadSlot"],
            true),
        new(
            "component.textBox.cursor.editor",
            "cursor",
            "Cursor",
            "component.cursor",
            ["textBox", "cursorSlot", "componentSlot"],
            true),
        new(
            "component.textBox.leftIconRow.editor",
            "iconRow",
            "Left icon row",
            "component.iconRow",
            ["textBox", "leftIconRowSlot"],
            true),
        new(
            "component.textBox.rightIconRow.editor",
            "iconRow",
            "Right icon row",
            "component.iconRow",
            ["textBox", "rightIconRowSlot"],
            true),
        new(
            "component.textBox.surface.editor",
            "surface",
            "Surface",
            "component.surface",
            ["textBox", "surfaceSlot"],
            true),
        new(
            "component.textInputBar.barSurface.editor",
            "surface",
            "Bar surface",
            "component.surface",
            ["textInput", "barSurfaceSlot"],
            false),
        new(
            "component.textInputBar.iconBar.editor",
            "iconBar",
            "Icon bar",
            "component.iconBar",
            ["textInput", "iconBarSlot"],
            true),
        new(
            "component.textInputBar.textBox.editor",
            "textBox",
            "Text box",
            "component.textBox",
            ["textInput", "textBoxSlot"],
            false),
    ];
}
