// Generated from scaffolding/modules/*.json. Do not edit manually.
// Modules: module.core.chat, module.core.chatList, module.core.lockScreen, module.core.socialPost
namespace Mockups.DesktopEditorShell.EditorShell;

public static class GeneratedModuleScaffoldEmbeddedSlots
{
    public static EmbeddedComponentSlotDefinition[] All { get; } =
    [
        new(
            "module.core.chat.bubbleVariant",
            "bubble",
            "Bubble",
            "component.bubble",
            ["conversation", "bubbleSlot"]),
        new(
            "module.core.chat.headerAvatar.editor",
            "avatar",
            "Header avatar",
            "component.avatar",
            ["conversation", "headerAvatarSlot"]),
        new(
            "module.core.chat.headerLeftIconRow.editor",
            "iconRow",
            "Left icon row",
            "component.iconRow",
            ["conversation", "headerLeftIconRowSlot"]),
        new(
            "module.core.chat.headerRightIconRow.editor",
            "iconRow",
            "Right icon row",
            "component.iconRow",
            ["conversation", "headerRightIconRowSlot"]),
        new(
            "module.core.chat.headerSurface.editor",
            "surface",
            "Header surface",
            "component.surface",
            ["conversation", "headerSurfaceSlot"]),
        new(
            "module.core.chat.keyboardVariant",
            "keyboard",
            "Keyboard",
            "component.keyboard",
            ["conversation", "keyboardSlot"]),
        new(
            "module.core.chat.textInputBarVariant",
            "textInputBar",
            "Text input bar",
            "component.textInputBar",
            ["conversation", "textInputBarSlot"]),
        new(
            "module.core.chatList.bottomIconBar",
            "iconBar",
            "Bottom Icon Bar",
            "component.iconBar",
            ["chatList", "bottomIconBarSlot"]),
        new(
            "module.core.chatList.list",
            "list",
            "List",
            "component.list",
            ["chatList", "listSlot"]),
        new(
            "module.core.chatList.navigationBar",
            "navigation_bar",
            "Navigation Bar",
            "component.navigation_bar",
            ["chatList", "navigationBarSlot"]),
        new(
            "module.core.chatList.stack",
            "componentStack",
            "Content Stack",
            "component.componentStack",
            ["chatList", "stackSlot"]),
        new(
            "module.core.chatList.statusBar",
            "status_bar",
            "Status Bar",
            "component.status_bar",
            ["chatList", "statusBarSlot"]),
        new(
            "module.core.chatList.topIconBar",
            "iconBar",
            "Top Icon Bar",
            "component.iconBar",
            ["chatList", "topIconBarSlot"]),
        new(
            "module.core.lockScreen.navigationBarVariant",
            "navigation_bar",
            "Navigation bar",
            "component.navigation_bar",
            ["lockScreen", "navigationBarSlot"]),
        new(
            "module.core.lockScreen.stackVariant",
            "componentStack",
            "Stack",
            "component.componentStack",
            ["lockScreen", "stackSlot"]),
        new(
            "module.core.lockScreen.statusBarVariant",
            "status_bar",
            "Status bar",
            "component.status_bar",
            ["lockScreen", "statusBarSlot"]),
        new(
            "module.core.socialPost.headerSurface",
            "surface",
            "Header surface",
            "component.surface",
            ["socialPost", "headerSurfaceSlot"]),
        new(
            "module.core.socialPost.row1Slot1.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row1Slot1AvatarSlot"]),
        new(
            "module.core.socialPost.row1Slot1.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row1Slot1IconSlot"]),
        new(
            "module.core.socialPost.row1Slot1.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row1Slot1LabelSlot"]),
        new(
            "module.core.socialPost.row1Slot2.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row1Slot2AvatarSlot"]),
        new(
            "module.core.socialPost.row1Slot2.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row1Slot2IconSlot"]),
        new(
            "module.core.socialPost.row1Slot2.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row1Slot2LabelSlot"]),
        new(
            "module.core.socialPost.row1Slot3.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row1Slot3AvatarSlot"]),
        new(
            "module.core.socialPost.row1Slot3.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row1Slot3IconSlot"]),
        new(
            "module.core.socialPost.row1Slot3.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row1Slot3LabelSlot"]),
        new(
            "module.core.socialPost.row1Slot4.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row1Slot4AvatarSlot"]),
        new(
            "module.core.socialPost.row1Slot4.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row1Slot4IconSlot"]),
        new(
            "module.core.socialPost.row1Slot4.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row1Slot4LabelSlot"]),
        new(
            "module.core.socialPost.row1Slot5.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row1Slot5AvatarSlot"]),
        new(
            "module.core.socialPost.row1Slot5.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row1Slot5IconSlot"]),
        new(
            "module.core.socialPost.row1Slot5.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row1Slot5LabelSlot"]),
        new(
            "module.core.socialPost.row2Slot1.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row2Slot1AvatarSlot"]),
        new(
            "module.core.socialPost.row2Slot1.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row2Slot1IconSlot"]),
        new(
            "module.core.socialPost.row2Slot1.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row2Slot1LabelSlot"]),
        new(
            "module.core.socialPost.row2Slot2.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row2Slot2AvatarSlot"]),
        new(
            "module.core.socialPost.row2Slot2.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row2Slot2IconSlot"]),
        new(
            "module.core.socialPost.row2Slot2.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row2Slot2LabelSlot"]),
        new(
            "module.core.socialPost.row2Slot3.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row2Slot3AvatarSlot"]),
        new(
            "module.core.socialPost.row2Slot3.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row2Slot3IconSlot"]),
        new(
            "module.core.socialPost.row2Slot3.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row2Slot3LabelSlot"]),
        new(
            "module.core.socialPost.row2Slot4.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row2Slot4AvatarSlot"]),
        new(
            "module.core.socialPost.row2Slot4.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row2Slot4IconSlot"]),
        new(
            "module.core.socialPost.row2Slot4.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row2Slot4LabelSlot"]),
        new(
            "module.core.socialPost.row2Slot5.avatar",
            "avatar",
            "Avatar variant",
            "component.avatar",
            ["socialPost", "row2Slot5AvatarSlot"]),
        new(
            "module.core.socialPost.row2Slot5.icon",
            "button",
            "Icon variant",
            "component.button",
            ["socialPost", "row2Slot5IconSlot"]),
        new(
            "module.core.socialPost.row2Slot5.label",
            "label",
            "Label variant",
            "component.label",
            ["socialPost", "row2Slot5LabelSlot"]),
    ];
}
