// Generated from scaffolding/modules/*.json. Do not edit manually.
// Modules: module.core.chat, module.core.chatList, module.core.lockScreen
using System.Collections.Generic;

namespace Mockups.DesktopEditorShell.EditorShell;

public static class GeneratedModuleScaffoldFieldCatalog
{
    public static void AddFields(
        Dictionary<string, RecordClassFieldDescriptor> fields)
    {
        fields.Add("module.core.chat.bubbleMaxWidth", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.bubbleMaxWidth","label":"Max width %","valueKind":"Integer","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":{"minimum":1,"maximum":100,"increment":1,"decimalPlaces":0,"useSlider":false},"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","bubbleMaxWidth"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.bubbleVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.bubbleVariant","label":"Bubble variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"bubble","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","bubbleSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerAvatar.editor", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerAvatar.editor","label":"Header avatar","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"avatar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerAvatarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerAvatarAlignment", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerAvatarAlignment","label":"Avatar alignment","valueKind":"OptionToken","isEditable":true,"options":[{"value":"left","label":"Left","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"center","label":"Center","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"right","label":"Right","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""}],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerAvatarAlignment"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerHeight", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerHeight","label":"Header height","valueKind":"Integer","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":{"minimum":0,"maximum":240,"increment":1,"decimalPlaces":0,"useSlider":false},"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerHeight"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerLeftIconRow.editor", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerLeftIconRow.editor","label":"Left icon row","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"iconRow","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerLeftIconRowSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerLeftIconRow.inputs", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerLeftIconRow.inputs","label":"Left row settings","valueKind":"ComponentInputBindings","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":[],"runtimeInputComponentVariantFieldId":"module.core.chat.headerLeftIconRow.editor","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerLeftIconRowInputs"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerRightIconRow.editor", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerRightIconRow.editor","label":"Right icon row","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"iconRow","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerRightIconRowSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerRightIconRow.inputs", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerRightIconRow.inputs","label":"Right row settings","valueKind":"ComponentInputBindings","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":[],"runtimeInputComponentVariantFieldId":"module.core.chat.headerRightIconRow.editor","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerRightIconRowInputs"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerSurface.editor", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerSurface.editor","label":"Header surface","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"surface","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerSurfaceSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.headerUseActorColor", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.headerUseActorColor","label":"Use actor color","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","headerUseActorColor"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.keyboardVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.keyboardVariant","label":"Keyboard variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"keyboard","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","keyboardSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.messageGap", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.messageGap","label":"Message gap","valueKind":"ThemeToken","isEditable":true,"options":[{"value":"theme.spacing.none","label":"spacing.none","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xs","label":"spacing.xs","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.s","label":"spacing.s","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.m","label":"spacing.m","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.l","label":"spacing.l","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xl","label":"spacing.xl","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xxl","label":"spacing.xxl","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""}],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","messageGap"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.messageMotion", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.messageMotion","label":"Messages motion","valueKind":"Motion","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","messageMotion"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.messageViewportMotion", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.messageViewportMotion","label":"Message viewport motion","valueKind":"Motion","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","messageViewportMotion"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.screenGutter", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.screenGutter","label":"Screen gutter","valueKind":"ThemeTokenPair","isEditable":true,"options":[{"value":"theme.spacing.none","label":"spacing.none","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xs","label":"spacing.xs","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.s","label":"spacing.s","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.m","label":"spacing.m","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.l","label":"spacing.l","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xl","label":"spacing.xl","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""},{"value":"theme.spacing.xxl","label":"spacing.xxl","colorHex":null,"isNeutral":false,"groupValue":"","groupLabel":"","localLabel":""}],"pairLabels":{"first":"X","second":"Y"},"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","screenGutter"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showHeader", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showHeader","label":"Header","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showHeader"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showHeaderSeparator", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showHeaderSeparator","label":"Show separator","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showHeaderSeparator"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showKeyboard", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showKeyboard","label":"Keyboard","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showKeyboard"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showNavigationBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showNavigationBar","label":"Navigation bar","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showNavigationBar"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showStatusBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showStatusBar","label":"Status bar","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showStatusBar"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.showTextInputBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.showTextInputBar","label":"Text input bar","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","showTextInputBar"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.textInputBarVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.textInputBarVariant","label":"Text input variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"textInputBar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","textInputBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chat.useAppWallpaper", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chat.useAppWallpaper","label":"Use app wallpaper","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["conversation","useAppWallpaper"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.bottomIconBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.bottomIconBar","label":"Bottom Icon Bar","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"iconBar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","bottomIconBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.list", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.list","label":"List","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"list","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","listSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.navigationBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.navigationBar","label":"Navigation Bar","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"navigation_bar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","navigationBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.stack", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.stack","label":"Content Stack","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"componentStack","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","stackSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.statusBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.statusBar","label":"Status Bar","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"status_bar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","statusBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.topIconBar", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.topIconBar","label":"Top Icon Bar","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"iconBar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","topIconBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.chatList.wallpaperEnabled", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.chatList.wallpaperEnabled","label":"Wallpaper","valueKind":"Boolean","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["chatList","wallpaperEnabled"],"optionSource":"None"}"""));
        fields.Add("module.core.lockScreen.navigationBarVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.lockScreen.navigationBarVariant","label":"Navigation bar variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"navigation_bar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["lockScreen","navigationBarSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.lockScreen.stackInputs", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.lockScreen.stackInputs","label":"Stack inputs","valueKind":"ComponentInputBindings","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"module.core.lockScreen.stackVariant","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["lockScreen","stackInputs"],"optionSource":"None"}"""));
        fields.Add("module.core.lockScreen.stackItems", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.lockScreen.stackItems","label":"Components","valueKind":"StructuredCollection","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"module.core.lockScreen.stackVariant","motionTiming":null,"configJsonPath":["lockScreen","stackInputs","items"],"optionSource":"None"}"""));
        fields.Add("module.core.lockScreen.stackVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.lockScreen.stackVariant","label":"Stack variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"componentStack","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["lockScreen","stackSlot"],"optionSource":"None"}"""));
        fields.Add("module.core.lockScreen.statusBarVariant", ScaffoldDictionaryFieldContract.Module("""{"id":"module.core.lockScreen.statusBarVariant","label":"Status bar variant","valueKind":"ComponentVariantSlot","isEditable":true,"options":[],"pairLabels":null,"imagePreview":null,"number":null,"recordReference":null,"componentVariantType":"status_bar","unit":"","componentInputBindings":null,"runtimeInputComponentVariantFieldId":"","runtimeCollectionComponentVariantFieldId":"","motionTiming":null,"configJsonPath":["lockScreen","statusBarSlot"],"optionSource":"None"}"""));
    }
}
