import type { FieldDescriptor } from "./types.js";

function bubbleStatusColorDescriptor(
  mode: "light" | "dark",
  property: string,
  label: string,
): FieldDescriptor {
  return {
    canonicalPath: `module.colors.chatBubbles.status.${property}.${mode}`,
    storagePath: ["modes", mode, "chatBubbles", "status", property],
    label,
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "Status",
    property,
    widget: "color",
  };
}

function bubbleMediaBorderColorDescriptor(mode: "light" | "dark"): FieldDescriptor {
  return {
    canonicalPath: `module.colors.chatBubbles.media.borderColor.${mode}`,
    storagePath: ["modes", mode, "chatBubbles", "media", "borderColor"],
    label: "Media border",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "Media",
    property: "borderColor",
    widget: "color",
  };
}

export const coreChatV1ContentDescriptors: FieldDescriptor[] = [
  {
    canonicalPath: "moduleInstance.content.messages[]",
    storagePath: ["messages", 0],
    label: "Message",
    section: "Module Content",
    area: "content",
    group: "Messages",
    summaryKeys: ["text", "media.filePath", "type", "id"],
  },
  {
    canonicalPath: "moduleInstance.content.messages[].actorId",
    storagePath: ["messages", 0, "actorId"],
    label: "Actor",
    section: "Module Content",
    area: "content",
    group: "Messages",
    property: "actorId",
  },
  {
    canonicalPath: "moduleInstance.content.messages[].text",
    storagePath: ["messages", 0, "text"],
    label: "Message text",
    section: "Module Content",
    area: "content",
    group: "Messages",
    property: "text",
    widget: "textarea",
  },
  {
    canonicalPath: "moduleInstance.content.messages[].status.text",
    storagePath: ["messages", 0, "status", "text"],
    label: "Status text",
    section: "Module Content",
    area: "content",
    group: "Messages",
    role: "Status",
    property: "text",
  },
  {
    canonicalPath: "moduleInstance.content.messages[].status.deliveryStatus",
    storagePath: ["messages", 0, "status", "deliveryStatus"],
    label: "Delivery status",
    section: "Module Content",
    area: "content",
    group: "Messages",
    role: "Status",
    property: "deliveryStatus",
    widget: "select",
    options: ["none", "sent", "delivered", "read", "failed"],
  },
];

export const coreChatV1BehaviorDescriptors: FieldDescriptor[] = [
  {
    canonicalPath: "moduleInstance.behavior.showHeader",
    storagePath: ["showHeader"],
    label: "Show header",
    section: "Behavior",
    area: "behavior",
    property: "showHeader",
    widget: "checkbox",
  },
  {
    canonicalPath: "moduleInstance.behavior.showStatusBar",
    storagePath: ["showStatusBar"],
    label: "Show status bar",
    section: "Behavior",
    area: "behavior",
    property: "showStatusBar",
    widget: "checkbox",
  },
  {
    canonicalPath: "moduleInstance.behavior.showKeyboard",
    storagePath: ["showKeyboard"],
    label: "Show keyboard",
    section: "Behavior",
    area: "behavior",
    property: "showKeyboard",
    widget: "checkbox",
  },
  {
    canonicalPath: "moduleInstance.behavior.initialScroll",
    storagePath: ["initialScroll"],
    label: "Initial scroll",
    section: "Behavior",
    area: "behavior",
    property: "initialScroll",
    widget: "select",
    options: ["top", "bottom", "keep_latest_visible"],
  },
  {
    canonicalPath: "moduleInstance.behavior.messageGrouping",
    storagePath: ["messageGrouping"],
    label: "Message grouping",
    section: "Behavior",
    area: "behavior",
    property: "messageGrouping",
    widget: "select",
    options: ["none", "bySender"],
  },
];

export const coreChatV1TokenDescriptors: FieldDescriptor[] = [
  {
    canonicalPath: "module.design.typography.message.family",
    storagePath: ["typography", "message", "fontFamily"],
    label: "Family",
    section: "Design",
    area: "design",
    group: "Typography",
    role: "Message",
    property: "family",
    widget: "font",
  },
  {
    canonicalPath: "module.design.typography.message.size",
    storagePath: ["typography", "message", "fontSize"],
    label: "Size",
    section: "Design",
    area: "design",
    group: "Typography",
    role: "Message",
    property: "size",
    widget: "number",
    min: 1,
    step: 1,
  },
  {
    canonicalPath: "module.design.typography.message.lineHeight",
    storagePath: ["typography", "message", "lineHeight"],
    label: "Line height",
    section: "Design",
    area: "design",
    group: "Typography",
    role: "Message",
    property: "lineHeight",
    widget: "number",
    min: 1,
    step: 1,
  },
  {
    canonicalPath: "module.design.typography.message.weight",
    storagePath: ["typography", "message", "fontWeight"],
    label: "Weight",
    section: "Design",
    area: "design",
    group: "Typography",
    role: "Message",
    property: "weight",
    widget: "select",
  },
  {
    canonicalPath: "module.design.header.height",
    storagePath: ["header", "height"],
    label: "Height",
    section: "Design",
    area: "design",
    group: "Header",
    property: "height",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.colors.header.background.light",
    storagePath: ["modes", "light", "header", "background"],
    label: "Background",
    section: "Colors",
    area: "colors",
    group: "Header",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.header.background.dark",
    storagePath: ["modes", "dark", "header", "background"],
    label: "Background",
    section: "Colors",
    area: "colors",
    group: "Header",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.incomingBackground.light",
    storagePath: ["modes", "light", "chatBubbles", "incomingBackground"],
    label: "Incoming background",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "Incoming",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.incomingBackground.dark",
    storagePath: ["modes", "dark", "chatBubbles", "incomingBackground"],
    label: "Incoming background",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "Incoming",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.systemBackground.light",
    storagePath: ["modes", "light", "chatBubbles", "systemBackground"],
    label: "System background",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "System",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.systemBackground.dark",
    storagePath: ["modes", "dark", "chatBubbles", "systemBackground"],
    label: "System background",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "System",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.systemText.light",
    storagePath: ["modes", "light", "chatBubbles", "systemText"],
    label: "System text",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "System",
    property: "text",
    widget: "color",
  },
  {
    canonicalPath: "module.colors.chatBubbles.systemText.dark",
    storagePath: ["modes", "dark", "chatBubbles", "systemText"],
    label: "System text",
    section: "Colors",
    area: "colors",
    group: "Chat Bubbles",
    role: "System",
    property: "text",
    widget: "color",
  },
  {
    canonicalPath: "module.design.chatBubbles.tail.style",
    storagePath: ["chatBubbles", "tail", "style"],
    label: "Tail style",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Tail",
    property: "style",
    widget: "select",
    options: ["rounded_wedge", "simple_triangle", "curved_hook", "cut_corner"],
  },
  {
    canonicalPath: "module.design.chatBubbles.shadow.enabled",
    storagePath: ["chatBubbles", "shadowEnabled"],
    label: "Bubble shadow",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Shadow",
    property: "enabled",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.surfaceRelief.enabled",
    storagePath: ["chatBubbles", "surfaceReliefEnabled"],
    label: "Bubble surface relief",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Relief",
    property: "enabled",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.messageLabel.useActorColor",
    storagePath: ["chatBubbles", "messageLabelUseActorColor"],
    label: "Use actor color",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Label",
    property: "useActorColor",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.messageLabel.offsetX",
    storagePath: ["chatBubbles", "messageLabelOffsetX"],
    label: "Offset X",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Label",
    property: "offsetX",
    widget: "number",
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.messageLabel.offsetY",
    storagePath: ["chatBubbles", "messageLabelOffsetY"],
    label: "Offset Y",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Label",
    property: "offsetY",
    widget: "number",
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.media.borderWidth",
    storagePath: ["chatBubbles", "media", "borderWidth"],
    label: "Border width",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Media",
    property: "borderWidth",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.media.cornerRadius",
    storagePath: ["chatBubbles", "media", "cornerRadius"],
    label: "Corner radius",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Media",
    property: "cornerRadius",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.media.shadow.enabled",
    storagePath: ["chatBubbles", "media", "shadowEnabled"],
    label: "Media shadow",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Media",
    property: "shadowEnabled",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.tail.position",
    storagePath: ["chatBubbles", "tail", "verticalPosition"],
    label: "Tail position",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Tail",
    property: "position",
    widget: "select",
    options: ["bottom", "top"],
  },
  {
    canonicalPath: "module.design.chatBubbles.tail.width",
    storagePath: ["chatBubbles", "tail", "width"],
    label: "Tail width",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Tail",
    property: "width",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.tail.height",
    storagePath: ["chatBubbles", "tail", "height"],
    label: "Tail height",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Tail",
    property: "height",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.tail.scale",
    storagePath: ["chatBubbles", "tail", "scale"],
    label: "Tail scale",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Tail",
    property: "scale",
    widget: "number",
    min: 0.01,
    step: 0.05,
  },
  {
    canonicalPath: "module.design.chatBubbles.status.showText",
    storagePath: ["chatBubbles", "status", "showText"],
    label: "Show status text",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "showText",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.status.showTicks",
    storagePath: ["chatBubbles", "status", "showTicks"],
    label: "Show ticks",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "showTicks",
    widget: "checkbox",
  },
  {
    canonicalPath: "module.design.chatBubbles.status.size",
    storagePath: ["chatBubbles", "status", "size"],
    label: "Status size",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "size",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.status.gap",
    storagePath: ["chatBubbles", "status", "gap"],
    label: "Status gap",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "gap",
    widget: "number",
    min: 0,
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.status.offsetX",
    storagePath: ["chatBubbles", "status", "offsetX"],
    label: "Status X offset",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "offsetX",
    widget: "number",
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.status.offsetY",
    storagePath: ["chatBubbles", "status", "offsetY"],
    label: "Status Y offset",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "offsetY",
    widget: "number",
    step: 1,
  },
  {
    canonicalPath: "module.design.chatBubbles.status.tickSingleIconToken",
    storagePath: ["chatBubbles", "status", "tickSingleIconToken"],
    label: "Single tick token",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "tickSingleIconToken",
  },
  {
    canonicalPath: "module.design.chatBubbles.status.tickDoubleIconToken",
    storagePath: ["chatBubbles", "status", "tickDoubleIconToken"],
    label: "Double tick token",
    section: "Design",
    area: "design",
    group: "Chat Bubbles",
    role: "Status",
    property: "tickDoubleIconToken",
  },
  ...(["light", "dark"] as const).flatMap((mode) => [
    bubbleMediaBorderColorDescriptor(mode),
    bubbleStatusColorDescriptor(mode, "textColor", "Status text"),
    bubbleStatusColorDescriptor(mode, "sentColor", "Sent"),
    bubbleStatusColorDescriptor(mode, "deliveredColor", "Delivered"),
    bubbleStatusColorDescriptor(mode, "readColor", "Read"),
    bubbleStatusColorDescriptor(mode, "failedColor", "Failed"),
  ]),
];
