import type { FieldDescriptor } from "./types.js";

export const themeTokenDescriptors: FieldDescriptor[] = [
  {
    canonicalPath: "theme.tokens.typography.body.family",
    storagePath: ["fonts", "family"],
    label: "Family",
    section: "Tokens",
    area: "tokens",
    group: "Typography",
    role: "Body",
    property: "family",
    widget: "font",
  },
  {
    canonicalPath: "theme.tokens.typography.body.size",
    storagePath: ["fonts", "bodySize"],
    label: "Size",
    section: "Tokens",
    area: "tokens",
    group: "Typography",
    role: "Body",
    property: "size",
    widget: "number",
    min: 1,
    step: 1,
  },
  {
    canonicalPath: "theme.tokens.typography.body.lineHeight",
    storagePath: ["fonts", "bodyLineHeight"],
    label: "Line height",
    section: "Tokens",
    area: "tokens",
    group: "Typography",
    role: "Body",
    property: "lineHeight",
    widget: "number",
    min: 1,
    step: 1,
  },
  {
    canonicalPath: "theme.tokens.typography.body.weight",
    storagePath: ["fonts", "weight"],
    label: "Weight",
    section: "Tokens",
    area: "tokens",
    group: "Typography",
    role: "Body",
    property: "weight",
    widget: "select",
  },
  {
    canonicalPath: "theme.tokens.colors.background.light",
    storagePath: ["modes", "light", "colors", "background"],
    label: "Background",
    section: "Colors",
    area: "colors",
    group: "Theme Colors",
    property: "background",
    widget: "color",
  },
  {
    canonicalPath: "theme.tokens.colors.background.dark",
    storagePath: ["modes", "dark", "colors", "background"],
    label: "Background",
    section: "Colors",
    area: "colors",
    group: "Theme Colors",
    property: "background",
    widget: "color",
  },
];
