using Avalonia;
using Avalonia.Controls;
using Avalonia.Layout;
using Avalonia.Media;
using Mockups.DesktopEditorShell.Common;
using Mockups.DesktopEditorShell.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mockups.DesktopEditorShell.EditorShell;

internal sealed class NavigationBarItemsCollectionEditor
{
    private readonly SpikeDatabase _database;
    private readonly bool _isDark;
    private readonly Func<string, ValueKind, Task<string?>> _browsePath;
    private readonly Action _onChanged;

    public NavigationBarItemsCollectionEditor(
        SpikeDatabase database,
        bool isDark,
        Func<string, ValueKind, Task<string?>> browsePath,
        Action onChanged)
    {
        _database = database;
        _isDark = isDark;
        _browsePath = browsePath;
        _onChanged = onChanged;
    }

    public InstantEditorCard Create(ProjectTreeNode node)
    {
        var icon = EditorIcons.Create(EditorIcons.Navigation, 18);
        var items = Items(node).ToList();
        var body = new StackPanel
        {
            Spacing = 10,
        };

        body.Children.Add(new TextBlock
        {
            Text = "Navigation buttons are generated by kind. Zone and order control placement inside the bar.",
            TextWrapping = TextWrapping.Wrap,
            Opacity = 0.72,
        });

        for (var index = 0; index < items.Count; index++)
        {
            body.Children.Add(CreateItemRow(node, index, items[index]));
        }

        return new InstantEditorCard(
            EditorCardHeader.Create("Button Items", $"{items.Count} generated buttons", icon),
            new Border
            {
                Padding = new Thickness(10),
                Child = body,
            },
            isExpanded: false)
        {
            HorizontalAlignment = HorizontalAlignment.Stretch,
        };
    }

    private Control CreateItemRow(ProjectTreeNode node, int index, SpikeDatabase.NavigationBarItem item)
    {
        var row = new Border
        {
            Padding = new Thickness(10),
            CornerRadius = new CornerRadius(10),
            BorderBrush = new SolidColorBrush(Color.Parse(_isDark ? "#34445A" : "#D0D7E2")),
            BorderThickness = new Thickness(1),
        };
        var panel = new StackPanel
        {
            Spacing = 8,
        };
        row.Child = panel;

        panel.Children.Add(new TextBlock
        {
            Text = $"{item.Label} · {item.Kind}",
            FontWeight = FontWeight.SemiBold,
        });

        panel.Children.Add(CreateInlineField(
            new FieldValue(
                new FieldDefinition(
                    $"navigationBar.items.{index}.zone",
                    "Zone",
                    ValueKind.OptionToken,
                    DefaultValue: item.Zone,
                    Options:
                    [
                        new FieldOption("off", "Off"),
                        new FieldOption("left", "Left"),
                        new FieldOption("center", "Center"),
                        new FieldOption("right", "Right"),
                    ]),
                item.Zone),
            (value) => UpdateItem(node, index, item with { Zone = value })));

        panel.Children.Add(CreateInlineField(
            new FieldValue(
                new FieldDefinition(
                    $"navigationBar.items.{index}.order",
                    "Order",
                    ValueKind.Integer,
                    DefaultValue: item.Order.ToString()),
                item.Order.ToString()),
            (value) => UpdateItem(node, index, item with { Order = NumericText.Int32(value, item.Order) })));

        return row;
    }

    private DictionaryFieldControl CreateInlineField(FieldValue fieldValue, Action<string> persist)
    {
        var control = new DictionaryFieldControl(fieldValue, _browsePath);
        control.ValueCommitted += (_, value) => persist(value);
        return control;
    }

    private void UpdateItem(ProjectTreeNode node, int index, SpikeDatabase.NavigationBarItem nextItem)
    {
        if (node.Kind == ProjectTreeNodeKind.ComponentClass)
        {
            _database.UpdateNavigationBarComponentItem(node.Id, index, nextItem);
        }
        else
        {
            _database.UpdateNavigationBarItem(node.Id, index, nextItem);
        }
        _onChanged();
    }

    private IReadOnlyList<SpikeDatabase.NavigationBarItem> Items(ProjectTreeNode node) =>
        node.Kind == ProjectTreeNodeKind.ComponentClass
            ? _database.GetNavigationBarComponentItems(node.Id)
            : _database.GetNavigationBarItems(node.Id);
}
