import {
  defineFields,
  type JsonFieldBinding,
} from "../value-system/index.js";

const GROUPS = {
  canvas: { id: "canvas", label: "Canvas" },
  designSpace: { id: "designSpace", label: "Design space" },
  rendering: { id: "rendering", label: "Rendering" },
  safeArea: { id: "safeArea", label: "Safe area" },
  screen: { id: "screen", label: "Screen" },
  statusBar: { id: "statusBar", label: "Status bar" },
  viewport: { id: "viewport", label: "Viewport" },
} as const;

export const DEVICE_FIELDS = defineFields({
  id: {
    id: "device.id",
    kind: "text",
    ui: {
      label: "ID",
    },
  },
  productionId: {
    id: "device.productionId",
    kind: "recordReference",
    ui: {
      label: "Production",
      tableId: "productions",
      labelColumn: "name",
    },
  },
  name: {
    id: "device.name",
    kind: "text",
    ui: {
      label: "Name",
    },
  },
  frameAssetId: {
    id: "device.frameAssetId",
    kind: "recordReference",
    ui: {
      label: "Frame asset",
      tableId: "media_assets",
      labelColumn: "name",
      allowEmpty: true,
    },
  },
  designWidth: {
    id: "device.metrics.designSpace.width",
    kind: "integer",
    defaultValue: 390,
    ui: {
      label: "Design width",
      group: GROUPS.designSpace,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.designSpace.size", label: "Size", role: "W" },
    },
  },
  designHeight: {
    id: "device.metrics.designSpace.height",
    kind: "integer",
    defaultValue: 844,
    ui: {
      label: "Design height",
      group: GROUPS.designSpace,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.designSpace.size", label: "Size", role: "H" },
    },
  },
  renderWidth: {
    id: "device.metrics.renderSize.width",
    kind: "integer",
    defaultValue: 1170,
    ui: {
      label: "Render width",
      group: GROUPS.rendering,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.renderSize", label: "Render size", role: "W" },
    },
  },
  renderHeight: {
    id: "device.metrics.renderSize.height",
    kind: "integer",
    defaultValue: 2532,
    ui: {
      label: "Render height",
      group: GROUPS.rendering,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.renderSize", label: "Render size", role: "H" },
    },
  },
  scaleToPixels: {
    id: "device.metrics.scaleToPixels",
    kind: "decimal",
    defaultValue: 3,
    ui: {
      label: "Scale to pixels",
      group: GROUPS.rendering,
      min: 0.01,
      step: 0.1,
    },
  },
  pixelRatio: {
    id: "device.metrics.pixelRatio",
    kind: "decimal",
    defaultValue: 3,
    ui: {
      label: "Pixel ratio",
      group: GROUPS.rendering,
      min: 0.01,
      step: 0.1,
    },
  },
  defaultScreenScale: {
    id: "device.metrics.defaultScreenScale",
    kind: "decimal",
    defaultValue: 1,
    ui: {
      label: "Default screen scale",
      group: GROUPS.rendering,
      min: 0.01,
      step: 0.01,
    },
  },
  canvasWidth: {
    id: "device.metrics.canvas.width",
    kind: "integer",
    defaultValue: 1170,
    ui: {
      label: "Canvas width",
      group: GROUPS.canvas,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.canvas.size", label: "Canvas size", role: "W" },
    },
  },
  canvasHeight: {
    id: "device.metrics.canvas.height",
    kind: "integer",
    defaultValue: 2532,
    ui: {
      label: "Canvas height",
      group: GROUPS.canvas,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.canvas.size", label: "Canvas size", role: "H" },
    },
  },
  screenX: {
    id: "device.metrics.screen.x",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Screen X",
      group: GROUPS.screen,
      step: 1,
      pair: { id: "device.metrics.screen.position", label: "Position", role: "X" },
    },
  },
  screenY: {
    id: "device.metrics.screen.y",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Screen Y",
      group: GROUPS.screen,
      step: 1,
      pair: { id: "device.metrics.screen.position", label: "Position", role: "Y" },
    },
  },
  screenWidth: {
    id: "device.metrics.screen.width",
    kind: "integer",
    defaultValue: 1170,
    ui: {
      label: "Screen width",
      group: GROUPS.screen,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.screen.size", label: "Size", role: "W" },
    },
  },
  screenHeight: {
    id: "device.metrics.screen.height",
    kind: "integer",
    defaultValue: 2532,
    ui: {
      label: "Screen height",
      group: GROUPS.screen,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.screen.size", label: "Size", role: "H" },
    },
  },
  viewportX: {
    id: "device.metrics.viewport.x",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Viewport X",
      group: GROUPS.viewport,
      step: 1,
      pair: { id: "device.metrics.viewport.position", label: "Position", role: "X" },
    },
  },
  viewportY: {
    id: "device.metrics.viewport.y",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Viewport Y",
      group: GROUPS.viewport,
      step: 1,
      pair: { id: "device.metrics.viewport.position", label: "Position", role: "Y" },
    },
  },
  viewportWidth: {
    id: "device.metrics.viewport.width",
    kind: "integer",
    defaultValue: 1170,
    ui: {
      label: "Viewport width",
      group: GROUPS.viewport,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.viewport.size", label: "Size", role: "W" },
    },
  },
  viewportHeight: {
    id: "device.metrics.viewport.height",
    kind: "integer",
    defaultValue: 2532,
    ui: {
      label: "Viewport height",
      group: GROUPS.viewport,
      min: 1,
      step: 1,
      pair: { id: "device.metrics.viewport.size", label: "Size", role: "H" },
    },
  },
  safeAreaTop: {
    id: "device.metrics.safeArea.top",
    kind: "integer",
    defaultValue: 160,
    ui: {
      label: "Safe top",
      group: GROUPS.safeArea,
      min: 0,
      step: 1,
      pair: { id: "device.metrics.safeArea.vertical", label: "Vertical", role: "Top" },
    },
  },
  safeAreaBottom: {
    id: "device.metrics.safeArea.bottom",
    kind: "integer",
    defaultValue: 91,
    ui: {
      label: "Safe bottom",
      group: GROUPS.safeArea,
      min: 0,
      step: 1,
      pair: { id: "device.metrics.safeArea.vertical", label: "Vertical", role: "Bottom" },
    },
  },
  safeAreaLeft: {
    id: "device.metrics.safeArea.left",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Safe left",
      group: GROUPS.safeArea,
      min: 0,
      step: 1,
      pair: { id: "device.metrics.safeArea.horizontal", label: "Horizontal", role: "Left" },
    },
  },
  safeAreaRight: {
    id: "device.metrics.safeArea.right",
    kind: "integer",
    defaultValue: 0,
    ui: {
      label: "Safe right",
      group: GROUPS.safeArea,
      min: 0,
      step: 1,
      pair: { id: "device.metrics.safeArea.horizontal", label: "Horizontal", role: "Right" },
    },
  },
  statusBarHeight: {
    id: "device.metrics.statusBar.height",
    kind: "integer",
    defaultValue: 160,
    ui: {
      label: "Height",
      group: GROUPS.statusBar,
      min: 0,
      step: 1,
    },
  },
  cornerRadius: {
    id: "device.metrics.cornerRadius",
    kind: "integer",
    defaultValue: 140,
    ui: {
      label: "Corner radius",
      group: GROUPS.screen,
      min: 0,
      step: 1,
    },
  },
});

export const DEVICE_COLUMN_BINDINGS = [
  { outputPath: ["id"], field: DEVICE_FIELDS.id },
  { outputPath: ["production_id"], field: DEVICE_FIELDS.productionId },
  { outputPath: ["name"], field: DEVICE_FIELDS.name },
  { outputPath: ["frame_asset_id"], field: DEVICE_FIELDS.frameAssetId },
] satisfies readonly JsonFieldBinding[];

export const DEVICE_METRICS_BINDINGS = [
  { outputPath: ["designSpace", "width"], field: DEVICE_FIELDS.designWidth },
  { outputPath: ["designSpace", "height"], field: DEVICE_FIELDS.designHeight },
  { outputPath: ["renderSize", "width"], field: DEVICE_FIELDS.renderWidth },
  { outputPath: ["renderSize", "height"], field: DEVICE_FIELDS.renderHeight },
  { outputPath: ["scaleToPixels"], field: DEVICE_FIELDS.scaleToPixels },
  { outputPath: ["pixelRatio"], field: DEVICE_FIELDS.pixelRatio },
  { outputPath: ["defaultScreenScale"], field: DEVICE_FIELDS.defaultScreenScale },
  { outputPath: ["canvas", "width"], field: DEVICE_FIELDS.canvasWidth },
  { outputPath: ["canvas", "height"], field: DEVICE_FIELDS.canvasHeight },
  { outputPath: ["screen", "x"], field: DEVICE_FIELDS.screenX },
  { outputPath: ["screen", "y"], field: DEVICE_FIELDS.screenY },
  { outputPath: ["screen", "width"], field: DEVICE_FIELDS.screenWidth },
  { outputPath: ["screen", "height"], field: DEVICE_FIELDS.screenHeight },
  { outputPath: ["viewport", "x"], field: DEVICE_FIELDS.viewportX },
  { outputPath: ["viewport", "y"], field: DEVICE_FIELDS.viewportY },
  { outputPath: ["viewport", "width"], field: DEVICE_FIELDS.viewportWidth },
  { outputPath: ["viewport", "height"], field: DEVICE_FIELDS.viewportHeight },
  { outputPath: ["safeArea", "top"], field: DEVICE_FIELDS.safeAreaTop },
  { outputPath: ["safeArea", "bottom"], field: DEVICE_FIELDS.safeAreaBottom },
  { outputPath: ["safeArea", "left"], field: DEVICE_FIELDS.safeAreaLeft },
  { outputPath: ["safeArea", "right"], field: DEVICE_FIELDS.safeAreaRight },
  { outputPath: ["statusBar", "height"], field: DEVICE_FIELDS.statusBarHeight },
  { outputPath: ["cornerRadius"], field: DEVICE_FIELDS.cornerRadius },
] satisfies readonly JsonFieldBinding[];
